### ISSUE TITLE
RuntimeError: Error building extension 'wkv_cuda'   无法打开文件“kernel32.lib”

### ISSUE THREAD

**Issue by flizzywine** [BlinkDL/ChatRWKV#115]
D:\AI\ChatRWKV>python chat.py

ChatRWKV v2 https://github.com/BlinkDL/ChatRWKV

Chinese - cuda fp16i8 *25 -> cpu fp32 - D:\AI\ChatRWKV/prompt/default/Chinese-2.py
Using C:\Users\admin\AppData\Local\torch_extensions\torch_extensions\Cache\py39_cu117 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file C:\Users\admin\AppData\Local\torch_extensions\torch_extensions\Cache\py39_cu117\wkv_cuda\build.ninja...
Building extension module wkv_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] "D:\Programs\Microsoft Visual Studio\VC\Tools\MSVC\14.35.32215\bin\Hostx64\x64/link.exe" wrapper.o operators.cuda.o /nologo /DLL c10.lib c10_cuda.lib torch_cpu.lib torch_cuda.lib -INCLUDE:?warp_size@cuda@at@@YAHXZ torch.lib /LIBPATH:D:\Programs\anaconda3\lib\site-packages\torch\lib torch_python.lib /LIBPATH:D:\Programs\anaconda3\libs "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\lib\x64" cudart.lib /out:wkv_cuda.pyd
FAILED: wkv_cuda.pyd 
"D:\Programs\Microsoft Visual Studio\VC\Tools\MSVC\14.35.32215\bin\Hostx64\x64/link.exe" wrapper.o operators.cuda.o /nologo /DLL c10.lib c10_cuda.lib torch_cpu.lib torch_cuda.lib -INCLUDE:?warp_size@cuda@at@@YAHXZ torch.lib /LIBPATH:D:\Programs\anaconda3\lib\site-packages\torch\lib torch_python.lib /LIBPATH:D:\Programs\anaconda3\libs "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\lib\x64" cudart.lib /out:wkv_cuda.pyd
LINK : fatal error LNK1104: 无法打开文件“kernel32.lib”
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "D:\Programs\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1893, in _run_ninja_build
    subprocess.run(
  File "D:\Programs\anaconda3\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\AI\ChatRWKV\chat.py", line 101, in <module>
    from rwkv.model import RWKV
  File "D:\Programs\anaconda3\lib\site-packages\rwkv\model.py", line 29, in <module>
    load(
  File "D:\Programs\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "D:\Programs\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "D:\Programs\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1624, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "D:\Programs\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1909, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'wkv_cuda'

**Comment by BlinkDL** [comment]
Can ask in QQ group 818930736
