### ISSUE TITLE
更新一下pip源的rwkv，不是github的最新版本，fp16i8会报错

### ISSUE THREAD

**Issue by StarWorkXc** [BlinkDL/ChatRWKV#119]
如题，如果有碰到相同问题的同学装一下git仓库内的rwkv就行，最新的rwkv修复了这个问题，三周了但是还没有放上pip中。
附报错片段：
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/rwkv/model.py", line 572, in forward
    ATT = self.cuda_att_seq if wtype != torch.uint8 else self.cuda_att_seq_i8
  File "/usr/local/lib/python3.9/site-packages/torch/jit/_script.py", line 502, in __getattr__
    return getattr(self._actual_script_module, attr)
  File "/usr/local/lib/python3.9/site-packages/torch/jit/_script.py", line 784, in __getattr__
    return super().__getattr__(attr)
  File "/usr/local/lib/python3.9/site-packages/torch/jit/_script.py", line 501, in __getattr__
    return super().__getattr__(attr)
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'RecursiveScriptModule' object has no attribute 'cuda_att_seq_i8'
```

**Comment by BlinkDL** [comment]
是国内的pip源没有更新。国外源是0.7.3

**Comment by StarWorkXc** [comment]
> 是国内的pip源没有更新。国外源是0.7.3

https://pypi.org/project/rwkv/#files
![image](https://github.com/BlinkDL/ChatRWKV/assets/73152103/205bdaca-afee-4c28-8243-db20232894b0)
pypi这个包的上传时间是 Apr 4, 2023 
model.py文件更新的时间是Apr 27, 2023

= =
