### ISSUE TITLE
demo true error ?

### ISSUE THREAD

**Issue by malv-c** [BlinkDL/ChatRWKV#166]
context changed to "assembly on linux"
--[ Trial 0 ]-----------------
assembly on linux-amd64.asm.d.
This assembler uses amd64 compiler to build the assembly.

In the
command line:
mvn clean install

In the
main.cmd:
cd /app/

In the
pkg/c/c
cd /app/c/c

In the
make.sh:
make -j2

In the
export JAVA_HOME=/path/to/jar/
JAVA_HOME=/path

--[ Trial 1 ]-----------------
assembly on linux
Traceback (most recent call last):
  File "/M/rwkv-cpp-accelerated/RWKV_v5_demo.py", line 232, in <module>
    tmp = tokenizer.decode(all_tokens[out_last:])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/M/rwkv-cpp-accelerated/RWKV_v5_demo.py", line 77, in decode
    return self.decodeBytes(tokens).decode('utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/M/rwkv-cpp-accelerated/RWKV_v5_demo.py", line 71, in decodeBytes
    return b''.join(map(lambda i: self.idx2token[i], tokens))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/M/rwkv-cpp-accelerated/RWKV_v5_demo.py", line 71, in <lambda>
    return b''.join(map(lambda i: self.idx2token[i], tokens))
                                  ~~~~~~~~~~~~~~^^^
KeyError: 0

on poor Intel(R) Celeron(R) N4100 it is usable ;)
please make a new demo with langchain and vulkan
thanks

**Comment by BlinkDL** [comment]
try https://github.com/josStorer/RWKV-Runner/releases
