### ISSUE TITLE
'No CUDA GPUs are available' in google colab with V100 GPU and high RAM

### ISSUE THREAD

**Issue by uxff** [BlinkDL/ChatRWKV#167]
I bought a colab pro, and ran this project with V100 GPU. It shows 'No CUDA GPUs are available'.

Version: v2
model: RWKV-4-Pile-3B-Chn-testNovel-done-ctx2048-20230312.pth
env: google colab, V100 gpu, 51G RAM.
strategy: cuda f16
language: Chinese

The command and output:
```
$ cd v2
$ python3 chat.py
ChatRWKV v2 https://github.com/BlinkDL/ChatRWKV

Chinese - cuda fp16 - /content/ChatRWKV/v2/prompt/default/Chinese-2.py
Loading model - /content/sample_data/RWKV-4-Pile-3B-Chn-testNovel-done-ctx2048-20230312.pth
RWKV_JIT_ON 1 RWKV_CUDA_ON 0 RESCALE_LAYER 6

Loading /content/sample_data/RWKV-4-Pile-3B-Chn-testNovel-done-ctx2048-20230312.pth ...
Strategy: (total 32+1=33 layers)
* cuda [float16, float16], store 33 layers
0-cuda-float16-float16 1-cuda-float16-float16 2-cuda-float16-float16 3-cuda-float16-float16 4-cuda-float16-float16 5-cuda-float16-float16 6-cuda-float16-float16 7-cuda-float16-float16 8-cuda-float16-float16 9-cuda-float16-float16 10-cuda-float16-float16 11-cuda-float16-float16 12-cuda-float16-float16 13-cuda-float16-float16 14-cuda-float16-float16 15-cuda-float16-float16 16-cuda-float16-float16 17-cuda-float16-float16 18-cuda-float16-float16 19-cuda-float16-float16 20-cuda-float16-float16 21-cuda-float16-float16 22-cuda-float16-float16 23-cuda-float16-float16 24-cuda-float16-float16 25-cuda-float16-float16 26-cuda-float16-float16 27-cuda-float16-float16 28-cuda-float16-float16 29-cuda-float16-float16 30-cuda-float16-float16 31-cuda-float16-float16 32-cuda-float16-float16 
emb.weight                        f16      cpu  50277  2560 
Traceback (most recent call last):
  File "/content/ChatRWKV/v2/chat.py", line 136, in <module>
    model = RWKV(model=args.MODEL_NAME, strategy=args.strategy)
  File "/usr/local/lib/python3.10/dist-packages/torch/jit/_script.py", line 292, in init_then_script
    original_init(self, *args, **kwargs)
  File "/content/ChatRWKV/v2/../rwkv_pip_package/src/rwkv/model.py", line 341, in __init__
    w[x] = w[x].to(device=DEVICE).contiguous()
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
```

**Comment by BlinkDL** [comment]
hi looks like some issue with your cuda installation

**Comment by uxff** [comment]
This problem can no longer happen.
