### ISSUE TITLE
running RWKV-4-Pile-7B-20230313-ctx8192-test380.pth with strategy "cuda fp16i8" failed

### ISSUE THREAD

**Issue by jcl2023** [BlinkDL/ChatRWKV#64]
I convert RWKV-4-Pile-7B-20230313-ctx8192-test380.pth with strategy "cuda fp16i8".
Then I run python chat with this converted model and strategy "cuda fp16i8", got the following error:
My graphics card has 12 GB VRAM.

Run prompt...
Traceback (most recent call last):
  File "/home/fc/2TB/GITS/ChatRWKV/v2/./chat.py", line 185, in <module>
    out = run_rnn(pipeline.encode(init_prompt))
  File "/home/fc/2TB/GITS/ChatRWKV/v2/./chat.py", line 156, in run_rnn
    out, model_state = model.forward(tokens[:CHUNK_LEN], model_state)
  File "/home/fc/anaconda3/envs/rwkv/lib/python3.10/site-packages/rwkv/model.py", line 607, in forward
    x, state[i*5+0], state[i*5+1], state[i*5+2], state[i*5+3] = ATT(
  File "/home/fc/anaconda3/envs/rwkv/lib/python3.10/site-packages/rwkv/model.py", line 531, in cuda_att_seq_i8
    r = torch.sigmoid(self.mm8_seq(rx, rw, rmx, rrx, rmy, rry))
  File "/home/fc/anaconda3/envs/rwkv/lib/python3.10/site-packages/rwkv/model.py", line 324, in mm8_seq
    return cuda_mm8_seq(B, N, M, x, w, mx, rx, my, ry)
  File "/home/fc/anaconda3/envs/rwkv/lib/python3.10/site-packages/rwkv/model.py", line 51, in cuda_mm8_seq
    assert x.shape == [B, N]
AssertionError

Any idea what I did wrong?

**Comment by BlinkDL** [comment]
pip install rwkv --upgrade
(upgrade to latest pip package)

**Comment by jcl2023** [comment]
@BlinkDL 

My rwkv is already the latest version. See below:

anaconda3/envs/rwkv/lib/python3.10/site-packages (0.7.1)
