### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by wlp233** [BlinkDL/ChatRWKV#85]
`Traceback (most recent call last):
  File "\ChatRWKV-main\ChatRWKV-main\chat.py", line 218, in <module>
    model = RWKV_RNN(args)
            ^^^^^^^^^^^^^^
  File "\ChatRWKV-main\ChatRWKV-main\venv\Lib\site-packages\torch\jit\_script.py", line 292, in init_then_script
    original_init(self, *args, **kwargs)
  File \ChatRWKV-main\ChatRWKV-main\src\model_run.py", line 75, in __init__
    w[x] = w[x].to(self.RUN_DEVICE)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "\ChatRWKV-main\ChatRWKV-main\venv\Lib\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

进程已结束,退出代码1
`

**Comment by BlinkDL** [comment]
Install torch 1.13.1+cu117
