### ISSUE TITLE
[Solved]AMD GPU[RX6600 8G] on Windows10 can work with DirectML now, but only the 1b5 model can load, it need 7.5G VRAM

### ISSUE THREAD

**Issue by FreeBlues** [BlinkDL/ChatRWKV#94]
AMD GPU[RX6600 8G] on Windows10 can work with DirectML, but only the 1b5 model can load, it need 7.5G VRAM.

## Updated 20230413 
Now it can support `3B` model, I create a fork for the Windows AMD GPU users, detailed here:
[ChatRWKV-DirectML](https://github.com/FreeBlues/ChatRWKV-DirectML)

---

### First need to install torch.directml

```
pip install torch-directml
```
>note: The torch version should be 1.13

### Then need to modify 2 files: 

`ChatRWKV/v2/chat.py` and `ChatRWKV/rwkv_pip_package/src/rwkv/model.py`:

####    in `chat.py`:

```
args.strategy = 'privateuse1 fp32'
```

####    in `model.py`

add the 2 lines first:

```
import torch.directml
dml = torch_directml.device()
```
Then hardcode modify all the device to `dml` in `model.py`:

line:85, modify to below:
```
STRATEGY_REGEX = r"^(?:(?:^|->) *(?:cuda(?::[\d]+)?|cpu|mps|privateuse1) (?:fp(?:16|32)|bf16)(?:i8|i4|i3)?(?: \*[\d]+\+?)? *)+$"
```

line:275, modify to below:
```
elif DEVICE != 'cpu':                       
    DEVICE = dml
    #print("device: ", DEVICE)
    w[x] = w[x].to(device=DEVICE).contiguous()
```

line:554, modify to below:
```
dd = self.strategy[i]
dev = dml
atype = dd.atype
state[i*5+0] = torch.zeros(args.n_embd, dtype=atype, requires_grad=False, device=dev).contiguous()
```

line:571, modify to below:
```
dd = self.strategy[i]
#dev = dd.device
dev = dml
atype = dd.atype
```

line:663, modify to below:
```
x = x[-1,:] if (seq_mode and (not full_output)) else x
#x = x.to(dtype=dd.atype, device=dd.device)
x = x.to(dtype=dd.atype, device=dml)
```

after that you can run it and see the GPU ram usage will reach 7.5G.

so only the 1b5 model can be used.

the response speed is faster then only cpu(1 char/sec), about 4~5 char per second.

## The run log::

```

(ChatRWKV) E:\Github\ChatRWKV\v2>python chat.py


ChatRWKV v2 https://github.com/BlinkDL/ChatRWKV

Chinese - privateuse1 fp32 - E:\Github\ChatRWKV\v2/prompt/default/Chinese-2.py
Loading model - ./fsx/BlinkDL/HF-MODEL/rwkv-4-pile-1b5/RWKV-4-Pile-1B5-EngChn-testNovel-done-ctx2048-20230225
RWKV_JIT_ON 1 RWKV_CUDA_ON 0 RESCALE_LAYER 0

Loading ./fsx/BlinkDL/HF-MODEL/rwkv-4-pile-1b5/RWKV-4-Pile-1B5-EngChn-testNovel-done-ctx2048-20230225.pth ...
Strategy: (total 24+1=25 layers)
* privateuse1 [float32, float32], store 25 layers
0-privateuse1-float32-float32 1-privateuse1-float32-float32 2-privateuse1-float32-float32 3-privateuse1-float32-float32 4-privateuse1-float32-float32 5-privateuse1-float32-float32 6-privateuse1-float32-float32 7-privateuse1-float32-float32 8-privateuse1-float32-float32 9-privateuse1-float32-float32 10-privateuse1-float32-float32 11-privateuse1-float32-float32 12-privateuse1-float32-float32 13-privateuse1-float32-float32 14-privateuse1-float32-float32 15-privateuse1-float32-float32 16-privateuse1-float32-float32 17-privateuse1-float32-float32 18-privateuse1-float32-float32 19-privateuse1-float32-float32 20-privateuse1-float32-float32 21-privateuse1-float32-float32 22-privateuse1-float32-float32 23-privateuse1-float32-float32 24-privateuse1-float32-float32
emb.weight                        f32      cpu  50277  2048
blocks.0.ln1.weight               f32 privateuseone:0   2048
blocks.0.ln1.bias                 f32 privateuseone:0   2048
blocks.0.ln2.weight               f32 privateuseone:0   2048
blocks.0.ln2.bias                 f32 privateuseone:0   2048
blocks.0.att.time_decay           f32 privateuseone:0   2048
blocks.0.att.time_first           f32 privateuseone:0   2048
blocks.0.att.time_mix_k           f32 privateuseone:0   2048
blocks.0.att.time_mix_v           f32 privateuseone:0   2048
blocks.0.att.time_mix_r           f32 privateuseone:0   2048
blocks.0.att.key.weight           f32 privateuseone:0   2048  2048
blocks.0.att.value.weight         f32 privateuseone:0   2048  2048
blocks.0.att.receptance.weight    f32 privateuseone:0   2048  2048
blocks.0.att.output.weight        f32 privateuseone:0   2048  2048
blocks.0.ffn.time_mix_k           f32 privateuseone:0   2048
blocks.0.ffn.time_mix_r           f32 privateuseone:0   2048
blocks.0.ffn.key.weight           f32 privateuseone:0   2048  8192
blocks.0.ffn.receptance.weight    f32 privateuseone:0   2048  2048
blocks.0.ffn.value.weight         f32 privateuseone:0   8192  2048
............................................................................................................................................................................................................................................................................................................................................................................................................
blocks.23.ln1.weight              f32 privateuseone:0   2048
blocks.23.ln1.bias                f32 privateuseone:0   2048
blocks.23.ln2.weight              f32 privateuseone:0   2048
blocks.23.ln2.bias                f32 privateuseone:0   2048
blocks.23.att.time_decay          f32 privateuseone:0   2048
blocks.23.att.time_first          f32 privateuseone:0   2048
blocks.23.att.time_mix_k          f32 privateuseone:0   2048
blocks.23.att.time_mix_v          f32 privateuseone:0   2048
blocks.23.att.time_mix_r          f32 privateuseone:0   2048
blocks.23.att.key.weight          f32 privateuseone:0   2048  2048
blocks.23.att.value.weight        f32 privateuseone:0   2048  2048
blocks.23.att.receptance.weight   f32 privateuseone:0   2048  2048
blocks.23.att.output.weight       f32 privateuseone:0   2048  2048
blocks.23.ffn.time_mix_k          f32 privateuseone:0   2048
blocks.23.ffn.time_mix_r          f32 privateuseone:0   2048
blocks.23.ffn.key.weight          f32 privateuseone:0   2048  8192
blocks.23.ffn.receptance.weight   f32 privateuseone:0   2048  2048
blocks.23.ffn.value.weight        f32 privateuseone:0   8192  2048
ln_out.weight                     f32 privateuseone:0   2048
ln_out.bias                       f32 privateuseone:0   2048
head.weight                       f32 privateuseone:0   2048 50277

Run prompt...
指令:
直接输入内容 --> 和机器人聊天（建议问机器人问题），用\n代表换行，必须用 Raven 模型
+ --> 让机器人换个回答
+reset --> 重置对话，请经常使用 +reset 重置机器人记忆

+i 某某指令 --> 问独立的问题（忽略聊天上下文），用\n代表换行，必须用 Raven 模型
+gen 某某内容 --> 续写内容（忽略聊天上下文），用\n代表换行，写小说用 testNovel 模型
+++ --> 继续 +gen / +i 的回答
++ --> 换个 +gen / +i 的回答

作者：彭博 请关注我的知乎: https://zhuanlan.zhihu.com/p/603840957
如果喜欢，请看我们的优质护眼灯: https://withablink.taobao.com

中文网文 testNovel 模型，可以试这些续写例子（不适合 Raven 模型！）：
+gen “区区
+gen 以下是不朽的科幻史诗长篇巨著，描写细腻，刻画了数百位个性鲜明的英雄和宏大的星际文明战争。\n第一章
+gen 这是一个修真世界，详细世界设定如下：\n1.

Chinese - ./fsx/BlinkDL/HF-MODEL/rwkv-4-pile-1b5/RWKV-4-Pile-1B5-EngChn-testNovel-done-ctx2048-20230225 - privateuse1 fp32

The following is a coherent verbose detailed conversation between a Chinese girl named Alice and her friend Bob. Alice is very intelligent, creative and friendly. Alice likes to tell Bob a lot about herself and her opinions. Alice usually gives Bob kind, helpful and informative advices.

Bob: lhc
Alice: LHC是指大型强子对撞机（Large Hadron Collider），是世界最大最强的粒子加速器，由欧洲核子中心（CERN）在瑞士日内瓦地 下建造。LHC的原理是加速质子（氢离子）并让它们相撞，让科学家研究基本粒子和它们之间的相互作用，并在2012年证实了希格斯玻色 子的存在。

Bob: 企鹅会飞吗
Alice: 企鹅是不会飞的。企鹅的翅膀短而扁平，更像是游泳时的一对桨。企鹅的身体结构和羽毛密度也更适合在水中游泳，而不是飞行 。

Bob: hi
Alice:E:\Github\ChatRWKV\v2/../rwkv_pip_package/src\rwkv\utils.py:78: UserWarning: The operator 'aten::multinomial' is not currently supported on the DML backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at D:\a\_work\1\s\pytorch-directml-plugin\torch_directml\csrc\dml\dml_cpu_fallback.cpp:17.)
  out = torch.multinomial(probs, num_samples=1)[0]
 企鹅是用来和人打电话的。企鹅通常带有亮色的边，比如“红”，“蓝”，“橙”，“绿”，“白”。因为信息传输是一种高能量光子方式，所以 企鹅的性能相当好。企鹅会飞时也会发射加速水流（Regenerative flow），形成超高速的水流。

Bob: +gen 爱丽丝进入了兔子洞，发现了一个奇怪的新世界
。
“这是什么东西？”爱丽丝疑惑地问。
爱丽丝探头一看，她惊呆了。
这里是一个巨大的兔子洞，兔子的尸体散乱地堆积在洞口。
地面有无数的血迹和深坑，一个狰狞的怪物从中爬了出来，就像变异之后的巨人一样，他的双臂粗壮如树枝，只有一个脑袋。
这个怪物竟然是一头骷髅！
第三百四十三章 寒风魔兽


Bob: +++
“这是……”爱丽丝呆住了。
巨大的怪物抬起脑袋，直勾勾地盯着她。
这是一个骷髅，一个头上长着狰狞血鬼骷髅的骷髅。
“不可能，这绝对不可能！”爱丽丝叫了起来。
“我当然没有骗你，你看我的身体！”那个怪物盯着爱丽丝说道。
他手一伸，拿出了一把精致的大弓，对准了爱丽丝。
“看来你不信我啊！”他吼道。
“你胡说八

Bob:
```

**Comment by FreeBlues** [comment]
I found in the `model.py`, a method named `torch.cuda.empty_cache()`was used, I think maybe it can make the GPU ram usage lower.
but in directML, without the similar method( in mps, it has `torch.mps.empty_cache()`), so the GPU ram usage is large.

**Comment by BlinkDL** [comment]
Try fp16 to save VRAM

**Comment by FreeBlues** [comment]
> Cool. Try fp16 to save VRAM

On my PC(48G Ram + 8G VRAM), only GPU VRAM can not load all the model, I need to use VRAM + CPU Ram, but the CPU Ram can not support Half, see below:

```
Run prompt...
Traceback (most recent call last):
  File "E:\Github\ChatRWKV-DirectML\v2\chat.py", line 195, in <module>
    out = run_rnn(pipeline.encode(init_prompt))
  File "E:\Github\ChatRWKV-DirectML\v2\chat.py", line 166, in run_rnn
    out, model_state = model.forward(tokens[:CHUNK_LEN], model_state)
  File "E:\Github\ChatRWKV-DirectML\v2/../rwkv_pip_package/src\rwkv\model.py", line 618, in forward
    x, state[i*5+0], state[i*5+1], state[i*5+2], state[i*5+3] = ATT(
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "E:\Github\ChatRWKV-DirectML\v2/../rwkv_pip_package/src\rwkv\model.py", line 449, in att_seq
    @MyFunction
    def att_seq(self, x, sx, aa, bb, pp, ln_w, ln_b, k_mix, v_mix, r_mix, t_decay, t_first, kw, vw, rw, ow, kmx, krx, kmy, kry, vmx, vrx, vmy, vry, rmx, rrx, rmy, rry, omx, orx, omy, ory):
        xx = F.layer_norm(x, (x.shape[-1],), weight=ln_w, bias=ln_b)
             ~~~~~~~~~~~~ <--- HERE
        sx = torch.cat((sx.unsqueeze(0), xx[:-1,:]))
        kx = xx * k_mix + sx * (1 - k_mix)
  File "E:\Users\admin\miniconda3\envs\ChatRWKV\lib\site-packages\torch\nn\functional.py", line 2515, in layer_norm
            layer_norm, (input, weight, bias), input, normalized_shape, weight=weight, bias=bias, eps=eps
        )
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
           ~~~~~~~~~~~~~~~~ <--- HERE
RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'
```
So the only 2 options I can use are `fp32` and `fp32i8`.

**Comment by BlinkDL** [comment]
What is your strategy?
Use fp16 for GPU layers, and fp32 for CPU layers

**Comment by FreeBlues** [comment]
> What is your strategy? Use fp16 for GPU layers, and fp32 for CPU layers

It looks like cant use fp16 on GPU and fp32  on CPU together.  return error.

My VRAM sttrategy:

```
args.strategy = 'privateuse1 fp16 *4 -> cpu fp32'
```


run log:

```
(ChatRWKV) E:\Github\ChatRWKV-DirectML\v2>python chat.py


ChatRWKV v2 https://github.com/BlinkDL/ChatRWKV

Chinese - privateuse1 fp16 *4 -> cpu fp32 - E:\Github\ChatRWKV-DirectML\v2/prompt/default/Chinese-2.py
Loading model - ./fsx/BlinkDL/HF-MODEL/rwkv-4-raven/RWKV-4-Raven-3B-v9-Eng99%-Other1%-20230411-ctx4096
RWKV_JIT_ON 1 RWKV_CUDA_ON 0 RESCALE_LAYER 6

Loading ./fsx/BlinkDL/HF-MODEL/rwkv-4-raven/RWKV-4-Raven-3B-v9-Eng99%-Other1%-20230411-ctx4096.pth ...
Strategy: (total 32+1=33 layers)
* privateuse1 [float16, float16], store 4 layers
* cpu [float32, float32], store 29 layers
0-privateuse1-float16-float16 1-privateuse1-float16-float16 2-privateuse1-float16-float16 3-privateuse1-float16-float16 4-cpu-float32-float32 5-cpu-float32-float32 6-cpu-float32-float32 7-cpu-float32-float32 8-cpu-float32-float32 9-cpu-float32-float32 10-cpu-float32-float32 11-cpu-float32-float32 12-cpu-float32-float32 13-cpu-float32-float32 14-cpu-float32-float32 15-cpu-float32-float32 16-cpu-float32-float32 17-cpu-float32-float32 18-cpu-float32-float32 19-cpu-float32-float32 20-cpu-float32-float32 21-cpu-float32-float32 22-cpu-float32-float32 23-cpu-float32-float32 24-cpu-float32-float32 25-cpu-float32-float32 26-cpu-float32-float32 27-cpu-float32-float32 28-cpu-float32-float32 29-cpu-float32-float32 30-cpu-float32-float32 31-cpu-float32-float32 32-cpu-float32-float32
emb.weight                        f16      cpu  50277  2560
blocks.0.ln1.weight               f16 privateuseone:0   2560
blocks.0.ln1.bias                 f16 privateuseone:0   2560
blocks.0.ln2.weight               f16 privateuseone:0   2560
blocks.0.ln2.bias                 f16 privateuseone:0   2560
blocks.0.att.time_decay           f32 privateuseone:0   2560
blocks.0.att.time_first           f32 privateuseone:0   2560
blocks.0.att.time_mix_k           f16 privateuseone:0   2560
blocks.0.att.time_mix_v           f16 privateuseone:0   2560
blocks.0.att.time_mix_r           f16 privateuseone:0   2560
blocks.0.att.key.weight           f16 privateuseone:0   2560  2560
blocks.0.att.value.weight         f16 privateuseone:0   2560  2560
blocks.0.att.receptance.weight    f16 privateuseone:0   2560  2560
blocks.0.att.output.weight        f16 privateuseone:0   2560  2560
blocks.0.ffn.time_mix_k           f16 privateuseone:0   2560
blocks.0.ffn.time_mix_r           f16 privateuseone:0   2560
blocks.0.ffn.key.weight           f16 privateuseone:0   2560 10240
blocks.0.ffn.receptance.weight    f16 privateuseone:0   2560  2560
blocks.0.ffn.value.weight         f16 privateuseone:0  10240  2560
............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
blocks.31.ln1.weight              f32      cpu   2560
blocks.31.ln1.bias                f32      cpu   2560
blocks.31.ln2.weight              f32      cpu   2560
blocks.31.ln2.bias                f32      cpu   2560
blocks.31.att.time_decay          f32      cpu   2560
blocks.31.att.time_first          f32      cpu   2560
blocks.31.att.time_mix_k          f32      cpu   2560
blocks.31.att.time_mix_v          f32      cpu   2560
blocks.31.att.time_mix_r          f32      cpu   2560
blocks.31.att.key.weight          f32      cpu   2560  2560
blocks.31.att.value.weight        f32      cpu   2560  2560
blocks.31.att.receptance.weight   f32      cpu   2560  2560
blocks.31.att.output.weight       f32      cpu   2560  2560
blocks.31.ffn.time_mix_k          f32      cpu   2560
blocks.31.ffn.time_mix_r          f32      cpu   2560
blocks.31.ffn.key.weight          f32      cpu   2560 10240
blocks.31.ffn.receptance.weight   f32      cpu   2560  2560
blocks.31.ffn.value.weight        f32      cpu  10240  2560
ln_out.weight                     f32      cpu   2560
ln_out.bias                       f32      cpu   2560
head.weight                       f32      cpu   2560 50277

Run prompt...
Traceback (most recent call last):
  File "E:\Github\ChatRWKV-DirectML\v2\chat.py", line 196, in <module>
    out = run_rnn(pipeline.encode(init_prompt))
  File "E:\Github\ChatRWKV-DirectML\v2\chat.py", line 167, in run_rnn
    out, model_state = model.forward(tokens[:CHUNK_LEN], model_state)
  File "E:\Github\ChatRWKV-DirectML\v2/../rwkv_pip_package/src\rwkv\model.py", line 618, in forward
    x, state[i*5+0], state[i*5+1], state[i*5+2], state[i*5+3] = ATT(
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "E:\Github\ChatRWKV-DirectML\v2/../rwkv_pip_package/src\rwkv\model.py", line 449, in att_seq
    @MyFunction
    def att_seq(self, x, sx, aa, bb, pp, ln_w, ln_b, k_mix, v_mix, r_mix, t_decay, t_first, kw, vw, rw, ow, kmx, krx, kmy, kry, vmx, vrx, vmy, vry, rmx, rrx, rmy, rry, omx, orx, omy, ory):
        xx = F.layer_norm(x, (x.shape[-1],), weight=ln_w, bias=ln_b)
             ~~~~~~~~~~~~ <--- HERE
        sx = torch.cat((sx.unsqueeze(0), xx[:-1,:]))
        kx = xx * k_mix + sx * (1 - k_mix)
  File "E:\Users\admin\miniconda3\envs\ChatRWKV\lib\site-packages\torch\nn\functional.py", line 2515, in layer_norm
            layer_norm, (input, weight, bias), input, normalized_shape, weight=weight, bias=bias, eps=eps
        )
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
           ~~~~~~~~~~~~~~~~ <--- HERE
RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'


(ChatRWKV) E:\Github\ChatRWKV-DirectML\v2>
```

**Comment by BlinkDL** [comment]
I guess fp32 for everything then...

**Comment by FreeBlues** [comment]
> I guess fp32 for everything then...

fp32 is ok, but in 8G VRAM GPU, it is slow, maybe 16G is needed

**Comment by pengan1987** [comment]
You might try PR https://github.com/BlinkDL/ChatRWKV/pull/174
It's just 6 lines change to use DirectML device for inference.
set the enviroment variable RWKV_DML_ON=1 and use "dml" in the strategy like
```python
os.environ['RWKV_DML_ON'] = '1'
args.strategy = 'dml fp16'
```
I don't have a AMD card, but cross verified on RTX3060 12GB and i5 7200u/Intel HD620 (20GB Shared RAM/VRAM) with all layers loaded as fp16 on GPU, about 7.6GB VRAM consumed with `RWKV-4-World-3B-v1-20230619-ctx4096.pth`, in this case, even HD620 iGPU can achieve 1.6s/word.
