### ISSUE TITLE
'RecursiveScriptModule' object has no attribute 'cuda_att_seq_i8'

### ISSUE THREAD

**Issue by webpolis** [BlinkDL/ChatRWKV#96]
```
(base) ✘-1 desktop:~/dev/projects/ai/ChatRWKV [main|✚ 2]> RWKV_CUDA_ON=1 python convert_model.py --strategy 'cuda fp16i8 *10+' --out ~/data/ai/models/RWKV/RWKV-4-Raven-14B-v8-EngAndMore-20230408-ctx4096.strat-16i8 --in ~/data/ai/models/RWKV/RWKV-4-Raven-14B-v8-EngAndMore-20230408-ctx4096.pth
(base) ✘-INT desktop:~/dev/projects/ai/ChatRWKV [main|✚ 2]> 
(base) ✘-INT desktop:~/dev/projects/ai/ChatRWKV [main|✚ 2]> python v2/chat.py 


ChatRWKV v2 https://github.com/BlinkDL/ChatRWKV

English - cuda fp16i8 *10+ - /media/nico/data/projects/ai/ChatRWKV/v2/prompt/default/English-2.py
Loading model - /home/nico/data/ai/models/RWKV/RWKV-4-Raven-14B-v8-EngAndMore-20230408-ctx4096.strat-16i8.pth
RWKV_JIT_ON 1 RWKV_CUDA_ON 1 RESCALE_LAYER 6

Loading /home/nico/data/ai/models/RWKV/RWKV-4-Raven-14B-v8-EngAndMore-20230408-ctx4096.strat-16i8.pth ...
Converted model: strategy cuda fp16i8 *10+, version 0.7

Strategy: (total 40+1=41 layers)
* cuda [float16, uint8], store 10 layers, stream 31 layers
0-cuda-float16-uint8 1-cuda-float16-uint8 2-cuda-float16-uint8 3-cuda-float16-uint8 4-cuda-float16-uint8 5-cuda-float16-uint8 6-cuda-float16-uint8 7-cuda-float16-uint8 8-cuda-float16-uint8 9-cuda-float16-uint8 10-cuda-float16-uint8-stream 11-cuda-float16-uint8-stream 12-cuda-float16-uint8-stream 13-cuda-float16-uint8-stream 14-cuda-float16-uint8-stream 15-cuda-float16-uint8-stream 16-cuda-float16-uint8-stream 17-cuda-float16-uint8-stream 18-cuda-float16-uint8-stream 19-cuda-float16-uint8-stream 20-cuda-float16-uint8-stream 21-cuda-float16-uint8-stream 22-cuda-float16-uint8-stream 23-cuda-float16-uint8-stream 24-cuda-float16-uint8-stream 25-cuda-float16-uint8-stream 26-cuda-float16-uint8-stream 27-cuda-float16-uint8-stream 28-cuda-float16-uint8-stream 29-cuda-float16-uint8-stream 30-cuda-float16-uint8-stream 31-cuda-float16-uint8-stream 32-cuda-float16-uint8-stream 33-cuda-float16-uint8-stream 34-cuda-float16-uint8-stream 35-cuda-float16-uint8-stream 36-cuda-float16-uint8-stream 37-cuda-float16-uint8-stream 38-cuda-float16-uint8-stream 39-cuda-float16-uint8-stream 40-cuda-float16-uint8-stream 
emb.weight                        f16      cpu  50277  5120 
blocks.0.ln1.weight               f16   cuda:0   5120       
blocks.0.ln1.bias                 f16   cuda:0   5120       
blocks.0.ln2.weight               f16   cuda:0   5120       
blocks.0.ln2.bias                 f16   cuda:0   5120       
blocks.0.att.time_decay           f32   cuda:0   5120       
blocks.0.att.time_first           f32   cuda:0   5120       
blocks.0.att.time_mix_k           f16   cuda:0   5120       
blocks.0.att.time_mix_v           f16   cuda:0   5120       
blocks.0.att.time_mix_r           f16   cuda:0   5120       
blocks.0.att.key.weight            i8   cuda:0   5120  5120 
blocks.0.att.value.weight          i8   cuda:0   5120  5120 
blocks.0.att.receptance.weight     i8   cuda:0   5120  5120 
blocks.0.att.output.weight         i8   cuda:0   5120  5120 
blocks.0.ffn.time_mix_k           f16   cuda:0   5120       
blocks.0.ffn.time_mix_r           f16   cuda:0   5120       
blocks.0.ffn.key.weight            i8   cuda:0   5120 20480 
blocks.0.ffn.receptance.weight     i8   cuda:0   5120  5120 
blocks.0.ffn.value.weight          i8   cuda:0  20480  5120 
............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
blocks.39.ln1.weight              f16   cuda:0   5120       
blocks.39.ln1.bias                f16   cuda:0   5120       
blocks.39.ln2.weight              f16   cuda:0   5120       
blocks.39.ln2.bias                f16   cuda:0   5120       
blocks.39.att.time_decay          f32   cuda:0   5120       
blocks.39.att.time_first          f32   cuda:0   5120       
blocks.39.att.time_mix_k          f16   cuda:0   5120       
blocks.39.att.time_mix_v          f16   cuda:0   5120       
blocks.39.att.time_mix_r          f16   cuda:0   5120       
blocks.39.att.key.weight           i8      cpu   5120  5120  (pinned)
blocks.39.att.value.weight         i8      cpu   5120  5120  (pinned)
blocks.39.att.receptance.weight    i8      cpu   5120  5120  (pinned)
blocks.39.att.output.weight        i8      cpu   5120  5120  (pinned)
blocks.39.ffn.time_mix_k          f16   cuda:0   5120       
blocks.39.ffn.time_mix_r          f16   cuda:0   5120       
blocks.39.ffn.key.weight           i8      cpu   5120 20480  (pinned)
blocks.39.ffn.receptance.weight    i8      cpu   5120  5120  (pinned)
blocks.39.ffn.value.weight         i8      cpu  20480  5120  (pinned)
ln_out.weight                     f16   cuda:0   5120       
ln_out.bias                       f16   cuda:0   5120       
head.weight                        i8   cuda:0   5120 50277 
blocks.0.att.key.weight_mx        f16   cuda:0   5120       
blocks.0.att.key.weight_my        f16   cuda:0   5120       
blocks.0.att.key.weight_rx        f16   cuda:0   5120       
blocks.0.att.key.weight_ry        f16   cuda:0   5120       
blocks.0.att.value.weight_mx      f16   cuda:0   5120       
blocks.0.att.value.weight_my      f16   cuda:0   5120       
blocks.0.att.value.weight_rx      f16   cuda:0   5120       
blocks.0.att.value.weight_ry      f16   cuda:0   5120       
blocks.0.att.receptance.weight_mx  f16   cuda:0   5120       
blocks.0.att.receptance.weight_my  f16   cuda:0   5120       
blocks.0.att.receptance.weight_rx  f16   cuda:0   5120       
blocks.0.att.receptance.weight_ry  f16   cuda:0   5120       
blocks.0.att.output.weight_mx     f16   cuda:0   5120       
blocks.0.att.output.weight_my     f16   cuda:0   5120       
blocks.0.att.output.weight_rx     f16   cuda:0   5120       
blocks.0.att.output.weight_ry     f16   cuda:0   5120       
blocks.0.ffn.key.weight_mx        f16   cuda:0  20480       
blocks.0.ffn.key.weight_my        f16   cuda:0   5120       
blocks.0.ffn.key.weight_rx        f16   cuda:0  20480       
blocks.0.ffn.key.weight_ry        f16   cuda:0   5120       
blocks.0.ffn.receptance.weight_mx  f16   cuda:0   5120       
blocks.0.ffn.receptance.weight_my  f16   cuda:0   5120       
blocks.0.ffn.receptance.weight_rx  f16   cuda:0   5120       
blocks.0.ffn.receptance.weight_ry  f16   cuda:0   5120       
blocks.0.ffn.value.weight_my      f16   cuda:0  20480       
blocks.0.ffn.value.weight_mx      f16   cuda:0   5120       
blocks.0.ffn.value.weight_rx      f16   cuda:0   5120       
blocks.0.ffn.value.weight_ry      f16   cuda:0  20480       
........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
blocks.39.att.key.weight_mx       f16   cuda:0   5120       
blocks.39.att.key.weight_my       f16   cuda:0   5120       
blocks.39.att.key.weight_rx       f16   cuda:0   5120       
blocks.39.att.key.weight_ry       f16   cuda:0   5120       
blocks.39.att.value.weight_mx     f16   cuda:0   5120       
blocks.39.att.value.weight_my     f16   cuda:0   5120       
blocks.39.att.value.weight_rx     f16   cuda:0   5120       
blocks.39.att.value.weight_ry     f16   cuda:0   5120       
blocks.39.att.receptance.weight_mx  f16   cuda:0   5120       
blocks.39.att.receptance.weight_my  f16   cuda:0   5120       
blocks.39.att.receptance.weight_rx  f16   cuda:0   5120       
blocks.39.att.receptance.weight_ry  f16   cuda:0   5120       
blocks.39.att.output.weight_mx    f16   cuda:0   5120       
blocks.39.att.output.weight_my    f16   cuda:0   5120       
blocks.39.att.output.weight_rx    f16   cuda:0   5120       
blocks.39.att.output.weight_ry    f16   cuda:0   5120       
blocks.39.ffn.key.weight_mx       f16   cuda:0  20480       
blocks.39.ffn.key.weight_my       f16   cuda:0   5120       
blocks.39.ffn.key.weight_rx       f16   cuda:0  20480       
blocks.39.ffn.key.weight_ry       f16   cuda:0   5120       
blocks.39.ffn.receptance.weight_mx  f16   cuda:0   5120       
blocks.39.ffn.receptance.weight_my  f16   cuda:0   5120       
blocks.39.ffn.receptance.weight_rx  f16   cuda:0   5120       
blocks.39.ffn.receptance.weight_ry  f16   cuda:0   5120       
blocks.39.ffn.value.weight_my     f16   cuda:0  20480       
blocks.39.ffn.value.weight_mx     f16   cuda:0   5120       
blocks.39.ffn.value.weight_rx     f16   cuda:0   5120       
blocks.39.ffn.value.weight_ry     f16   cuda:0  20480       
head.weight_mx                    f16   cuda:0  50277       
head.weight_my                    f16   cuda:0   5120       
head.weight_rx                    f16   cuda:0  50277       
head.weight_ry                    f16   cuda:0   5120       

Run prompt...
Traceback (most recent call last):
  File "/media/nico/data/projects/ai/ChatRWKV/v2/chat.py", line 188, in <module>
    out = run_rnn(pipeline.encode(init_prompt))
  File "/media/nico/data/projects/ai/ChatRWKV/v2/chat.py", line 153, in run_rnn
    out, model_state = model.forward(tokens[:CHUNK_LEN], model_state)
  File "/home/nico/anaconda3/lib/python3.10/site-packages/rwkv/model.py", line 572, in forward
    ATT = self.cuda_att_seq if wtype != torch.uint8 else self.cuda_att_seq_i8
  File "/home/nico/anaconda3/lib/python3.10/site-packages/torch/jit/_script.py", line 502, in __getattr__
    return getattr(self._actual_script_module, attr)
  File "/home/nico/anaconda3/lib/python3.10/site-packages/torch/jit/_script.py", line 784, in __getattr__
    return super().__getattr__(attr)
  File "/home/nico/anaconda3/lib/python3.10/site-packages/torch/jit/_script.py", line 501, in __getattr__
    return super().__getattr__(attr)
  File "/home/nico/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'RecursiveScriptModule' object has no attribute 'cuda_att_seq_i8'
```

I suspect there is a dependency issue, but I'm probably wrong. If anyone has an idea, please share.

**Comment by webpolis** [comment]
For reference, I just fixed this by declaring the **RWKV_CUDA_ON** environment variable before running the script.
