### ISSUE TITLE
RuntimeError: Error building extension 'wkv_cuda'

### ISSUE THREAD

**Issue by linkerlin** [BlinkDL/ChatRWKV#97]
version: repo master latest
when:
os.environ["RWKV_CUDA_ON"] = '1' 
got:
ChatRWKV v2 https://github.com/BlinkDL/ChatRWKV

English - cuda fp16i8 - /media/linker/690fc2d2-1cf4-4486-9bd8-746706772c1d1/linker/pys/ChatRWKV/v2/prompt/default/English-2.py
Using /home/linker/.cache/torch_extensions/py310_cu118 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/linker/.cache/torch_extensions/py310_cu118/wkv_cuda/build.ninja...
Building extension module wkv_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: error: stat(/media/linker/690fc2d2-1cf4-4486-9bd8-746706772c1d/linker/pys/ChatRWKV/rwkv_pip_package/src/rwkv/cuda/wrapper.cpp): Permission denied
Traceback (most recent call last):
  File "/home/linker/.local/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
    subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/media/linker/690fc2d2-1cf4-4486-9bd8-746706772c1d1/linker/pys/ChatRWKV/v2/chat.py", line 100, in <module>
    from rwkv.model import RWKV
  File "/media/linker/690fc2d2-1cf4-4486-9bd8-746706772c1d1/linker/pys/ChatRWKV/v2/../rwkv_pip_package/src/rwkv/model.py", line 29, in <module>
    load(
  File "/home/linker/.local/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/home/linker/.local/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/linker/.local/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1624, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/linker/.local/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'wkv_cuda'

--------------------------

when:
os.environ["RWKV_CUDA_ON"] = '0' 
is OK!

**Comment by linkerlin** [comment]
Fixed it.
uninstall jittor framework and downgrade torch from 2.0 to 1.13.1
And it work fine for me now.
